### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jackmerrill**
:trollface:

### CODE REVIEW

**Review by doamatto — CHANGES_REQUESTED** [review]
Needs to be more clever.

**Comment by doamatto** [comment]
Give me the biggest "funny" you've got, as the kids say.

**Review by doamatto — CHANGES_REQUESTED** [review]
That is so like you (the comment on the SASS literally says `// AAA compliant`).

image

**Comment by jackmerrill** [comment]
you said "biggest funny"

**Comment by doamatto** [comment]
biggest funny without killing society.

**Comment by doamatto** [comment]
Ye olde PR.

**Pull request closed without merging**
